version: '3'
services:
  postgresdb:
    image: "postgres:${POSTGRES_VERSION}"
    container_name: storage-api-db
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PWD}"
    ports:
      - "5432:5432"
    networks:
      - default
