version: '3'
services:
  postgresdb:
    build: .
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    container_name: storage-api-db
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    links:
      - "minio:service"
  minio:
    image: minio/minio
    container_name: minio-storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      timeout: 25s
      interval: 7s
      retries: 5
    restart: always
    environment:
      MINIO_ROOT_USER: "${MINIO_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_PASSWORD}"
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data
