server:
  port: 6001
  error:
    include-message: always
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
        show_sql: true
        use_sql_comments: false
        format_sql: false
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        enable_lazy_load_no_trans: true
        default_schema: ${POSTGRES_DEFAULT_SCHEMA}
    hibernate:
      ddl-auto: none
    open-in-view: true
  datasource:
    dbcp2:
      test-while-idle: true
      validation-query: 'SELECT 1'
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}'
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PWD}
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 150MB
      max-request-size: 150MB
  minio:
    url : ${MINIO_URL}
    bucket: cloud-trace-data-files
    access-key: ${MINIO_USER}
    secret-key: ${MINIO_PASSWORD}
